name: developci
kind: pipeline
stages:
  - name: first
    parallel: false
    steps:
      - name: first
        category: source
        plugin: for割接
        imagePullPolicy: if-not-present
        version: 0.0.1
        image: alpine
        settings:
          age: '26'
          key:
            secret: jeffreyzheng
            secretKey: password
          name: llia
          addr: cici
        privileged: false
        mode: plugin
  - name: second
    parallel: false
    steps:
      - name: second
        category: custom
        imagePullPolicy: if-not-present
        commands:
          - echo $app_name
          - echo "color=$color"
          - echo "age=$age"
          - echo $key
          - echo $secret
        image: alpine
        privileged: false
variables:
  - name: color
    type: string
    required: true
    description: 喜欢的颜色
    value: reds
  - name: age
    type: int
    required: true
    value: '38'
    description: ''
  - name: secret
    type: secret
    required: true
    value: '{"secret":"jeffreyzheng","secretKey":"password"}'
    description: eeefew
  - name: app_name
    type: string
    required: true
    description: ''
